### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by willianpaixao** [willianpaixao/spoon#1]
The repository reached a very stable version, everything is working and tested. I need some documentation to give a fast start for someone who wants to get started.

**Comment by saideepd** [comment]
@willianpaixao What do you want in README.md and is your project about some kind of books ?

**Comment by willianpaixao** [comment]
@saideepd  it's a repository with useful  playbooks for managing Raspberry Pi's with Ansible. An Getting Started like README would be nice. How to install, how to run and the current build status under TravisCI tool.

**Comment by saideepd** [comment]
@willianpaixao I have created a README.md for spoon & made a PR. Please review the PR and I hope that my PR gets merged.
